SchoolVoting/Models/Utilizador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SchoolVoting.Models
{
    public class Utilizador
    {
        [Key]
        public int UtlizadorId { get; set; }

        [Required(ErrorMessage = "Campo {0} obrigatório!")]
        [StringLength(100, ErrorMessage = "O campo {0} deve conter no máx. {1} e mín. {2} caracters",
            MinimumLength = 7)]
        [Display(Name = "E-Mail")]
        [DataType(DataType.EmailAddress)]
        [Index("EMailIndex", IsUnique = true)]
        public string EMail { get; set; }


        [Required(ErrorMessage = "Campo {0} obrigatório!")]
        [StringLength(50, ErrorMessage = "O campo {0} deve conter no máx. {1} e mín. {2} caracters",
            MinimumLength = 2)]
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Campo {0} obrigatório!")]
        [StringLength(50, ErrorMessage = "O campo {0} deve conter no máx. {1} e mín. {2} caracters",
            MinimumLength = 2)]
        [Display(Name = "Apelido")]
        public string Apelido { get; set; }

        [Display(Name = "Nome Completo")]
        public string FullName { get {return string.Format("{0} {1}",Nome,Apelido) ;} }

        [Required(ErrorMessage = "Campo {0} obrigatório!")]
        [StringLength(15, ErrorMessage = "O campo {0} deve conter no máx. {1} e mín. {2} caracters",
            MinimumLength = 7)]
        public string Telefone { get; set; }



        [Required(ErrorMessage = "Campo {0} obrigatório!")]
        [StringLength(100, ErrorMessage = "O campo {0} deve conter no máx. {1} e mín. {2} caracters",
            MinimumLength = 4)]
        [Display(Name = "Endereço")]
        public string Endereco { get; set; }

        [Display(Name = "Nível")]
        public string Nivel { get; set; }
        public string Grupo { get; set; }


        [DataType(DataType.ImageUrl)]
        [StringLength(300, ErrorMessage = "O campo {0} deve conter no máx. {1} e mín. {2} caracters",
            MinimumLength = 4)]
        public string Foto { get; set; }

        public virtual ICollection<GroupMember> GroupMembers { get; set; }

    }
}

SchoolVoting/Models/UtilizadorView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SchoolVoting.Models
{
    public class UtilizadorView
    {
        public int UtlizadorId { get; set; }

        [Required(ErrorMessage = "Campo {0} obrigatório!")]
        [StringLength(100, ErrorMessage = "O campo {0} deve conter no máx. {1} e mín. {2} caracters",
            MinimumLength = 7)]
        [Display(Name = "E-Mail")]
        [DataType(DataType.EmailAddress)]
        public string EMail { get; set; }


        [Required(ErrorMessage = "Campo {0} obrigatório!")]
        [StringLength(50, ErrorMessage = "O campo {0} deve conter no máx. {1} e mín. {2} caracters",
            MinimumLength = 2)]
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Campo {0} obrigatório!")]
        [StringLength(50, ErrorMessage = "O campo {0} deve conter no máx. {1} e mín. {2} caracters",
            MinimumLength = 2)]
        [Display(Name = "Apelido")]
        public string Apelido { get; set; }

        [Required(ErrorMessage = "Campo {0} obrigatório!")]
        [StringLength(15, ErrorMessage = "O campo {0} deve conter no máx. {1} e mín. {2} caracters",
            MinimumLength = 7)]
        public string Telefone { get; set; }



        [Required(ErrorMessage = "Campo {0} obrigatório!")]
        [StringLength(100, ErrorMessage = "O campo {0} deve conter no máx. {1} e mín. {2} caracters",
            MinimumLength = 4)]
        [Display(Name = "Endereço")]
        public string Endereco { get; set; }

        [Display(Name = "Nível")]
        public string Nivel { get; set; }
        public string Grupo { get; set; }

       public HttpPostedFileBase Foto { get; set; }
    }
}

SchoolVoting/Controllers/UtilizadorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolVoting.Models;
using System.IO;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace SchoolVoting.Controllers
{
    [Authorize]
    public class UtilizadorsController : Controller
    {
        private VotoContext db = new VotoContext();

        // GET: Utilizadors
        public ActionResult Index()
        {
            return View(db.Utilizadors.ToList());
        }

        // GET: Utilizadors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilizador utilizador = db.Utilizadors.Find(id);
            if (utilizador == null)
            {
                return HttpNotFound();
            }
            return View(utilizador);
        }

        // GET: Utilizadors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Utilizadors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UtilizadorView utilizadorView)
        {
            if (!ModelState.IsValid)
            {
                return View(utilizadorView);
            }

            string cam = string.Empty;
            string pic = string.Empty;
            if (utilizadorView.Foto != null)
            {
                pic = Path.GetFileName(utilizadorView.Foto.FileName);
                cam = Path.Combine(Server.MapPath("~/Content/Fotos"),pic);
                utilizadorView.Foto.SaveAs(cam);
                using (MemoryStream ms = new MemoryStream())
                {
                    utilizadorView.Foto.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                }
            }

            var utilizador = new Utilizador
            {
                EMail = utilizadorView.EMail,
                Nome = utilizadorView.Nome,
                Apelido = utilizadorView.Apelido,
                Telefone = utilizadorView.Telefone,
                Endereco = utilizadorView.Endereco,
                Nivel = utilizadorView.Nivel,
                Grupo = utilizadorView.Grupo,
                Foto = pic == string.Empty ? string.Empty : string.Format("~/Content/Fotos/{0}",pic)
            };

            db.Utilizadors.Add(utilizador);
            try
            {
                db.SaveChanges();
                this.CreateASPuser(utilizadorView);
            }
            catch (Exception ex)
            {
                if (ex.InnerException != null && 
                    ex.InnerException.InnerException != null && 
                    ex.InnerException.InnerException.Message.Contains("EMailIndex"))
                {
                    ViewBag.Error = "Esse Email está sendo utilizado por outro!!";
                }
                else
                {
                    ViewBag.Error = ex.Message;
                }
                return View(utilizadorView);
           }            
            return RedirectToAction("Index");            
        }

        private void CreateASPuser(UtilizadorView utilizadorView)
        {
            var utilizadorContext = new ApplicationDbContext();
            var utilizadorManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(utilizadorContext));
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(utilizadorContext));

            string roleName = "Utilizador";

            if (!roleManager.RoleExists(roleName))
            {
                roleManager.Create(new IdentityRole(roleName));
            }

            //Create the ASP.NET user
            var userASP = new ApplicationUser
            {
                UserName = utilizadorView.EMail,
                Email = utilizadorView.EMail,
                PhoneNumber=utilizadorView.Telefone,
            };

            utilizadorManager.Create(userASP, userASP.UserName);

            //Add user to role
            userASP = utilizadorManager.FindByName(utilizadorView.EMail);
            utilizadorManager.AddToRole(userASP.Id, "Utilizador"); 
        }

        // GET: Utilizadors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var utilizador = db.Utilizadors.Find(id);
            if (utilizador == null)
            {
                return HttpNotFound();
            }
            var utilizadorView = new UtilizadorView
            {
                EMail = utilizador.EMail,
                Nome = utilizador.Nome,
                Apelido = utilizador.Apelido,
                Telefone = utilizador.Telefone,
                Endereco = utilizador.Endereco,
                Nivel = utilizador.Nivel,
                Grupo = utilizador.Grupo,
                UtlizadorId=utilizador.UtlizadorId,
                //Foto = pic == string.Empty ? string.Empty : string.Format("~/Content/Fotos/{0}", pic)

            };
            return View(utilizadorView);

        }

        // POST: Utilizadors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UtilizadorView utilizadorView)
        {
            if (!ModelState.IsValid)
            {
                return View(utilizadorView);
            }

            string cam = string.Empty;
            string pic = string.Empty;
            if (utilizadorView.Foto != null)
            {
                pic = Path.GetFileName(utilizadorView.Foto.FileName);
                cam = Path.Combine(Server.MapPath("~/Content/Fotos"), pic);
                utilizadorView.Foto.SaveAs(cam);
                using (MemoryStream ms = new MemoryStream())
                {
                    utilizadorView.Foto.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                }
            }

            var utilizador = db.Utilizadors.Find(utilizadorView.UtlizadorId);

            utilizador.Nome = utilizadorView.Nome;
            utilizador.Apelido = utilizadorView.Apelido;
            utilizador.Telefone = utilizadorView.Telefone;
            utilizador.Endereco = utilizadorView.Endereco;
            utilizador.Nivel = utilizadorView.Nivel;
            utilizador.Grupo = utilizadorView.Grupo;

            if (!string.IsNullOrEmpty(pic))
            {
                utilizador.Foto = string.Format("~/Content/Fotos/{0}", pic);
            }


            db.Entry(utilizador).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Utilizadors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilizador utilizador = db.Utilizadors.Find(id);
            if (utilizador == null)
            {
                return HttpNotFound();
            }
            return View(utilizador);
        }

        // POST: Utilizadors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Utilizador utilizador = db.Utilizadors.Find(id);
            db.Utilizadors.Remove(utilizador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolVoting/Views/Utilizadors/Create.cshtml
@model SchoolVoting.Models.Utilizador

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<h3>@ViewBag.Error</h3>


@using (Html.BeginForm("Create","Utilizadors",FormMethod.Post, new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Utilizador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EMail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apelido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apelido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apelido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nivel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nivel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nivel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.Foto, "", new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolVoting/Views/Utilizadors/Delete.cshtml
@model SchoolVoting.Models.Utilizador

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Utilizador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apelido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apelido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nivel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nivel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Foto))
            {
                <img src="@Url.Content(Model.Foto)" , alt="Image" style="width:200px;height:200px;max-width: 100%; height: auto;" />
                //
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SchoolVoting/Views/Utilizadors/Details.cshtml
@model SchoolVoting.Models.Utilizador

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Utilizador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apelido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apelido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nivel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nivel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Foto))
            {
                <img src="@Url.Content(Model.Foto)" , alt="Image" style="width:200px;height:200px;max-width: 100%; height: auto;" />
                //
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UtlizadorId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SchoolVoting/Views/Utilizadors/Edit.cshtml
@model SchoolVoting.Models.UtilizadorView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Utilizadors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Utilizador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UtlizadorId)
        @Html.HiddenFor(model => model.EMail)




        @*<div class="form-group">
            @Html.LabelFor(model => model.EMail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMail, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apelido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apelido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apelido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nivel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nivel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nivel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.Foto, "", new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolVoting/Views/Utilizadors/Index.cshtml
@model IEnumerable<SchoolVoting.Models.Utilizador>

@{
    ViewBag.Title = "Index";
}

<h2>Gerir Utilizadores do Sistema</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EMail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apelido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Endereco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nivel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EMail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apelido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Endereco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nivel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grupo)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Foto)
        </td>*@
        <td>
            @if (!string.IsNullOrEmpty(item.Foto))
            {
                <img src="@Url.Content(item.Foto)" , alt="Image" style="width:100px;height:100px;" />
                //max - width: 100 %; height: auto;
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UtlizadorId }) |
            @Html.ActionLink("Details", "Details", new { id=item.UtlizadorId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UtlizadorId })
        </td>
    </tr>
}

</table>